### ISSUE TITLE
Cleanup Items

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#48]
A few things need to be cleaned up involving iexfinance's setup as a package.

## Docstrings
- [x] Clean and verify all necessary docstrings

## Docs
- [x] Create CONTRIBUTING section of readme and docs
  - [x] Repair flake8 requirements
- [x] Test and verify all hyperlinks and images in docs

## Github
- [x] Create issue template
- [x] Create pull request template
